### ISSUE TITLE
request for different sets of worker nodes

### ISSUE THREAD

**Issue by apendofnor** [safespring-community/utilities#5]
Hi,

Feature request: Install multiple workers with  different flavours

Could you please change the terraform code so it is possible to use multiple vm flavours on the worker nodes.
I.E. 2 workers with flavor y, 6 workers with flavor x and 3 workers with flavour z.
Usage for enduser: Preferably by specifying in settings.yml amount of workers and their flavour.

Regards
Fredrik

**Comment by JarleB** [comment]
Thanks for the request. This sounds like a useful feature. We'll see what we can do about it.
